---
title: "Final Report"
subtitle: "due November 16, 2021 by 11:59 PM "
author: "Shelby Brown, Katie Lam, Kaeden Hill"
date: "10/31/21"
output: pdf_document
---

# Load Packages
```{r load-packages}
library(tidyverse) 
library(janitor)

knitr::opts_chunk$set(warning = FALSE, message = FALSE)
``` 

# Load Data
```{r load-data}
heart <- readr::read_csv("heart.csv")
```

# Data Analysis Plan
```{r mean-chol}
mean_cholesterol <- heart %>%
  group_by(ChestPainType) %>%
  summarize(mean_cholesterol = mean(Cholesterol))%>%
  print()
```

```{r bar-cholesterol, fig.height = 3, fig.width = 3}
mean_cholesterol %>%
  ggplot()+
  geom_col(mapping = aes(x = ChestPainType, y = mean_cholesterol,  fill = ChestPainType), position = "dodge")+
  	theme(legend.position = "none")+
    labs(title = "Mean Cholesterol Levels",
         subtitle = "By Chest Pain Type",
         x = "Chest Pain Type",
         y = "Mean Cholesterol Levels (mm/dL)")
```

# Grouping Variables
```{r cholesterol}
heart_grouped <- heart %>%
  mutate(chol_level = cut(Cholesterol,
                          breaks = c(-Inf, 120, 200, 239, Inf),
                          labels = c("Low", "Normal", "Intermediate", "High"),
                          right=FALSE))
```

```{r bloodpressure}
heart_grouped <- heart_grouped %>%
  mutate(press_level = cut(RestingBP,
                          breaks = c(-Inf, 120, 130, 140, Inf),
                          labels = c("Normal", "Elevated", "Hypertension 1", "Hypertension 2"),
                          right=FALSE))
```

# Counting Variables
```{r factor}
heart_grouped <- heart_grouped %>%
  mutate(Sex, sex_factor=ifelse(Sex=="M", 0,1)) %>%
  mutate(ExerciseAngina, exer_factor=ifelse(ExerciseAngina=="N", 0,1))
```

```{r count-sex}
sex_grouped <- heart_grouped %>%
  group_by(ChestPainType, sex_factor) %>%
  summarize(count = n())
```

```{r count-ex}
exer_grouped <- heart_grouped %>%
  group_by(ChestPainType, exer_factor) %>%
  summarize(count = n())
```

```{r count-RBP}
RBP_grouped <- heart_grouped %>%
  group_by(ChestPainType, press_level) %>%
  summarize(count = n())
```

```{r count-cholesterol}
chol_grouped <- heart_grouped %>%
  group_by(ChestPainType, chol_level)%>%
  summarize(count = n())
```

# Visualizing Data
```{r sex-visuals}
sex_grouped %>%
  mutate(sex_factor, sex_name=ifelse(sex_factor==0, "Male","Female")) %>%
  ggplot()+
  geom_col(aes(x = ChestPainType, y = count, fill = as.factor(sex_name)), position = "fill") +
  labs(title = "Frequency of Chest Pain Type by Sex",
       x = "Chest Pain Type",
       y = "Count",
       fill = "Sex")
```

```{r exer-visuals}
exer_grouped %>%
  mutate(exer_factor, exer_cat=ifelse(exer_factor==0, "No","Yes")) %>%
  ggplot()+
  geom_col(aes(x = ChestPainType, y = count, fill = as.factor(exer_cat)), position = "fill") +
  labs(title = "Frequency of Chest Pain Type by Exercise Level",
       x = "Chest Pain Type",
       y = "Count",
       fill = "Exercise Induced Angina Status")
```

```{r BP-visuals}
RBP_grouped %>%
  ggplot()+
  geom_col(aes(x = ChestPainType, y = count, fill = as.factor(press_level)), position = "fill") +
  labs(title = "Frequency of Chest Pain Type by Blood Pressure Level",
       x = "Chest Pain Type",
       y = "Count",
       fill = "Blood Pressure Level")
```

```{r chol-visuals}
chol_grouped %>%
  ggplot()+
  geom_col(aes(x = ChestPainType, y = count, fill = as.factor(chol_level)), position = "fill") +
  labs(title = "Frequency of Chest Pain Type by Cholesterol Level",
       x = "Chest Pain Type",
       y = "Count",
       fill = "Cholesterol Level")
```

# Statistical Tests
```{r sex-table}
sex_table <- heart_grouped %>%
  tabyl(Sex, ChestPainType)

exer_table <- heart_grouped %>%
  tabyl(ExerciseAngina, ChestPainType)

RBP_table <- heart_grouped %>%
  tabyl(press_level, ChestPainType)

chol_table <- heart_grouped %>%
  tabyl(chol_level, ChestPainType)
```

```{r chisq}
chisq.test(sex_table)
chisq.test(exer_table)
```

```{r chi-squared}
chisq.test(chol_table)
chisq.test(RBP_table)
```

```{r step-down-cholesterol}
heart_grouped2 <- heart_grouped %>%
  filter(ChestPainType %in% c("ATA", "ASY")) 

chol_step <- heart_grouped2 %>%
  tabyl(chol_level, ChestPainType)
fisher.test(chol_step)

heart_grouped3 <- heart_grouped %>%
  filter(ChestPainType %in% c("ASY", "NAP")) 

chol_step2 <- heart_grouped3 %>%
  tabyl(chol_level, ChestPainType)
fisher.test(chol_step2)

heart_grouped4 <- heart_grouped %>%
  filter(ChestPainType %in% c("TA", "ASY")) 

chol_step3 <- heart_grouped4 %>%
  tabyl(chol_level, ChestPainType)
fisher.test(chol_step3)

heart_grouped5 <- heart_grouped %>%
  filter(ChestPainType %in% c("ATA", "NAP")) 

chol_step4 <- heart_grouped5 %>%
  tabyl(chol_level, ChestPainType)
fisher.test(chol_step4)

heart_grouped6 <- heart_grouped %>%
  filter(ChestPainType %in% c("ATA", "TA")) 

chol_step5 <- heart_grouped6 %>% #NOT SIGNIFICANT; used fisher bc count was <10 for low:TA
  tabyl(chol_level, ChestPainType)
fisher.test(chol_step5)

heart_grouped7 <- heart_grouped %>%
  filter(ChestPainType %in% c("NAP", "TA")) 

chol_step6 <- heart_grouped7 %>% #NOT SIGNIFICANT
  tabyl(chol_level, ChestPainType)
fisher.test(chol_step6)
```

```{r step-down-sex}
sex_step <- heart_grouped2 %>%
  tabyl(Sex, ChestPainType)
fisher.test(sex_step)

sex_step2 <- heart_grouped3 %>%
  tabyl(Sex, ChestPainType)
fisher.test(sex_step2)

sex_step3 <- heart_grouped4 %>% #NOT SIGNIFICANT
  tabyl(Sex, ChestPainType)
fisher.test(sex_step3)

sex_step4 <- heart_grouped5 %>% #NOT SIGNIFICANT
  tabyl(Sex, ChestPainType)
fisher.test(sex_step4)

sex_step5 <- heart_grouped6 %>% #NOT SIGNIFICANT
  tabyl(Sex, ChestPainType)
fisher.test(sex_step5)

sex_step6 <- heart_grouped7 %>% #NOT SIGNIFICANT
  tabyl(Sex, ChestPainType)
fisher.test(sex_step6)
```

```{r step-down-exercise}
exer_step <- heart_grouped2 %>%
  tabyl(ExerciseAngina, ChestPainType)
fisher.test(exer_step)

exer_step2 <- heart_grouped3 %>%
  tabyl(ExerciseAngina, ChestPainType)
fisher.test(exer_step2)

exer_step3 <- heart_grouped4 %>% 
  tabyl(ExerciseAngina, ChestPainType)
fisher.test(exer_step3)

exer_step4 <- heart_grouped5 %>% 
  tabyl(ExerciseAngina, ChestPainType)
fisher.test(exer_step4)

exer_step5 <- heart_grouped6 %>% #NOT SIGNIFICANT
  tabyl(ExerciseAngina, ChestPainType)
fisher.test(exer_step5)

exer_step6 <- heart_grouped7 %>% #NOT SIGNIFICANT
  tabyl(ExerciseAngina, ChestPainType)
fisher.test(exer_step6)
```

```{r step-down-RBP}
RBP_step <- heart_grouped2 %>%
  tabyl(press_level, ChestPainType)
fisher.test(RBP_step)

RBP_step2 <- heart_grouped3 %>% #NOT SIG
  tabyl(press_level, ChestPainType)
fisher.test(RBP_step2)

RBP_step3 <- heart_grouped4 %>% #NOT SIG
  tabyl(press_level, ChestPainType)
fisher.test(RBP_step3)

RBP_step4 <- heart_grouped5 %>% 
  tabyl(press_level, ChestPainType)
fisher.test(RBP_step4)

RBP_step5 <- heart_grouped6 %>% 
  tabyl(press_level, ChestPainType)
fisher.test(RBP_step5)

RBP_step6 <- heart_grouped7 %>% #NOT SIG
  tabyl(press_level, ChestPainType)
fisher.test(RBP_step6)
```

# Visualized Results

```{r graph1}

heart_grouped2 %>%
  ggplot()+
  geom_bar(mapping = aes(x = chol_level, fill = ChestPainType), position = "dodge")+
  labs(title = "")

```



